version: '2'
services:
   mysql:
     restart: always
     hostname: mysql
     build: ./mysql
     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
     volumes:
       - "$PWD/data:/var/lib/mysql"
     networks:
       hms_net:
         ipv4_address: "172.16.238.13"

   asset:
     build: ./asset
     networks:
       hms_net:
         ipv4_address: "172.16.238.11"
     volumes:
       - "$PWD/asset/gestion:/usr/share/nginx/html/example"
     restart: always

   api:
     build: ./api
     networks:
       hms_net:
         ipv4_address: "172.16.238.12"
     depends_on:
       - mysql
     volumes:
       - "$PWD/api/gestion-api:/usr/src/app"
     restart: always
     links:
       - mysql
     command: flask run -h 0.0.0.0

networks:
   hms_net:
     driver: bridge
     driver_opts:
       com.docker.network.enable_ipv6: "false"
     ipam:
       driver: default
       config:
         - subnet: "172.16.238.0/24"
           gateway: "172.16.238.1"
